final defaultConfig = {
  "use_default": true,
  "board": {
    "height": 8,
    "width": 8,
    "arrangement": {
      "0 0": "white rook",
      "1 0": "white knight",
      "2 0": "white bishop",
      "3 0": "white queen",
      "4 0": "white king",
      "5 0": "white bishop",
      "6 0": "white knight",
      "7 0": "white rook",
      "0 1": "white pawn",
      "1 1": "white pawn",
      "2 1": "white pawn",
      "3 1": "white pawn",
      "4 1": "white pawn",
      "5 1": "white pawn",
      "6 1": "white pawn",
      "7 1": "white pawn",
      "0 6": "black pawn",
      "1 6": "black pawn",
      "2 6": "black pawn",
      "3 6": "black pawn",
      "4 6": "black pawn",
      "5 6": "black pawn",
      "6 6": "black pawn",
      "7 6": "black pawn",
      "0 7": "black rook",
      "1 7": "black knight",
      "2 7": "black bishop",
      "3 7": "black queen",
      "4 7": "black king",
      "5 7": "black bishop",
      "6 7": "black knight",
      "7 7": "black rook",
    }
  },
  "movements": null,
  "pieces": null,
};
